name: Auto Approve Self-PR

on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: github.actor == 'gauravgitlab'
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}